### ISSUE TITLE
[GSoC] RViz based on ignition rendering

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rviz#3]
# ROS 2
 - [ ] Target Foxy 
 - [ ] Instalation instructions
 - [ ] Fix `package.xml`
 - [ ] Fix linters

# Ignition gazebo
 - Tools for launching (similar to [gazebo_ros](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/kinetic-devel/gazebo_ros)) -> upstream https://github.com/ignitionrobotics/ros_ign/tree/dashing/ros_ign_gazebo

# Dynamic load of topics
 - right now topics are hardcode. Add a GUI to be able to add, remove, etc

RViZ has this one:
 ![](https://docs.ros.org/indigo/api/rviz/html/user_guide/_images/add-display-dialog.png)

# Demo
 - Be able to visualize `tf` when launching
```
ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py
```
 - https://index.ros.org/doc/ros2/Tutorials/dummy-robot-demo/

**Comment by ahcorde** [comment]
I have created this image where we should iterate during the GSoC.

![ign-rviz_v1](https://user-images.githubusercontent.com/1933907/82802778-b7ce3080-9e7f-11ea-9c78-4bc42462290b.png)

I colored in green the part that we can start working on

This image defined for now two main packages. 

 - **ign-rviz**. This package should create:
    -  a 3D scene
    - Initialize a ROS 2 node
    - Subscribed to `tf` and `tf_static`
    - Create displays to check:
       - Available Display plugins
       - Avaiblable topic
    - We can use some of the current plugins:
       - World stats
       - Grid_3d
       - Scene_3d

 - **ign-rviz-plugins**. This package should have the display plugins to dynamically load and unload topics in the 3D scene.
   - `tf`
   - `image` Follow ups in this Issue https://github.com/Sarath18/ign-rviz/issues/5

**Comment by Sarath18** [comment]
I have updated the architecture diagram for ign-rviz

![ign-rviz architecture_1](https://user-images.githubusercontent.com/33201532/83233087-d009bc80-a1ab-11ea-8247-a4750b9e312e.png)
![ign-rviz architecture_2](https://user-images.githubusercontent.com/33201532/83233093-d39d4380-a1ab-11ea-97d4-b88d5d608166.png)

Incremental updates:
- `MessageDisplayBase` class will be inherited by any visualization plugin type, implemented and exported to pluginlib.
- Restructured repository
  - **ign-rviz**: This is the main application and will house the main user interface and interaction implementation.
  - **ign-rviz-plugins**: This has the base message display class and will have the implementation of default visualization plugins.
  - **ign-rviz-common**: This will contain FrameManager class and other common classes (in the future) which will be needed by both the packages. Creating a common package will eliminate cyclic dependencies caused when the contents are places in either of ign-rviz or ign-rviz-plugins packages.
