### ISSUE TITLE
GPS Plugin Proposal

### ISSUE THREAD

**Issue by Sarath18** [ignitionrobotics/ign-rviz#65]
While searching for some map implementation available in qt/qml I came across this Maps plugin which supports osm, mapboxgl, and a few others. After experimenting with the Maps module, I have created a prototype for the plugin, which basically subscribes to `sensor_msgs/msg/NavSatFix` and draws a circle on that particular location. Here is a quick preview:

![gps](https://user-images.githubusercontent.com/33201532/97180239-cff40400-17bf-11eb-8741-0124f0a91239.gif)

I would like to know your thoughts on a GPS display plugin. If this sounds like a good idea, what other features can be added to this plugin?

**Comment by ahcorde** [comment]
Hi @Sarath18,

this plugin looks pretty interesting. When I have worked with drones, I always needed to open the Ground Control Station to check the real position of the drone. This plugin will allow the visualize this in the same tool. 

+1

**Comment by Sarath18** [comment]
I understand the issue. What I did to view the position of the robot was to write a node using `roslibjs`, subscribe to GPS data, and view the position using Google Maps API. So even I feel visualizing the GPS data in ign-rviz itself will be a great addition.

I have a rough code ready, I will wrap up things and open up a PR for the GPS plugin. 

Any other features which can be added to this plugin?

**Comment by chapulina** [comment]
This looks like an awesome idea!

> Any other features which can be added to this plugin?

An idea would be to also display the coordinate numbers.

It would also be cool to plot a larger circle around that is proportional to the covariance.
