### ISSUE TITLE
GlobalStatus plugin

### ISSUE THREAD

**Issue by atharva-18** [ignitionrobotics/ign-rviz#68]
I have created a plugin for displaying the current status of `Fixed Frame` within the tf tree. This is how it looks like -

- No tf data
  1. Ignition RViz
  ![ign-warn](https://user-images.githubusercontent.com/39728574/99687224-6909f800-2aaa-11eb-9df8-0212b3e5363d.png)
  2. RViz2
![rviz2-warn](https://user-images.githubusercontent.com/39728574/99687968-41675f80-2aab-11eb-99af-ddec0341201f.png)

- Error in tf data
  1. Ignition RViz
  ![ign-error](https://user-images.githubusercontent.com/39728574/99687626-e0d82280-2aaa-11eb-85bb-d8db13ef5701.png)
  2. RViz2
![rviz2-error](https://user-images.githubusercontent.com/39728574/99688027-56dc8980-2aab-11eb-8245-21d889d4f572.png)

- Ok message
  1. Ignition RViz
  ![ign-ok](https://user-images.githubusercontent.com/39728574/99688170-7ecbed00-2aab-11eb-90e8-20ba0683e7d5.png)
  2. RViz2
  ![rviz2-ok](https://user-images.githubusercontent.com/39728574/99688292-a15e0600-2aab-11eb-9ac3-92ba8bffe6ed.png)

 What other things can be added to this plugin?

**Comment by Sarath18** [comment]
Hello @atharva-18. Firstly, thank you for your previous contribution.

This looks like a great addition.  I was wondering if we could move this into the `GlobalOptions` plugin?
I am suggesting this because this new plugin, should be visible at all times, hence, will take up a lot of space (content + plugin title bar). This status can be easily integrated into the space left to spare in the `GlobalOptions` plugin.

> What other things can be added to this plugin?

We can add a tree view showing the status of all the available frames just like in RViz.

**Comment by atharva-18** [comment]
Hey @Sarath18. 



> I was wondering if we could move this into the `GlobalOptions` plugin?
> I am suggesting this because this new plugin, should be visible at all times, hence, will take up a lot of space (content + plugin title bar). This status can be easily integrated into the space left to spare in the `GlobalOptions` plugin.

Fair enough, I'll move this to the `GlobalOptions` plugin. 

> We can add a tree view showing the status of all the available frames just like in RViz.

We can show a QML TreeView for all tf frames. Each node in the tree will show the frame name, the number of received messages and validity based on the output of `FrameManager::getFramePose`. This seems pretty cool to me!

**Comment by atharva-18** [comment]
> Firstly, thank you for your previous contribution.

Glad to help :rocket:
