### ISSUE TITLE
`Scene3D` is deprecated from `Fortress`

### ISSUE THREAD

**Issue by ahcorde** [ignitionrobotics/ign-rviz#77]
`Scene3D` is deprecated from `Fortress`

We need to have two config files the existing one and another one with all the `MinimalScene` related plugins,

We can install the right config file [here](https://github.com/ignitionrobotics/ign-rviz/blob/main/ign_rviz/CMakeLists.txt#L108-L109).

**Comment by Thodoris1999** [comment]
I can be assigned to this if that's okay.

**Comment by ahcorde** [comment]
Sure :+1:
